---
jobs:
- name: atomy
  public: true
  plan:
  - get: atomy
    trigger: true
  - task: tests
    file: atomy/ci/tests.yml

resources:
- name: atomy
  type: git
  source:
    uri: https://github.com/vito/atomy
